import typing

import numpy as np

class AffineScalarFunc:
    nominal_value: float
    std_dev: float
    def __repr__(self) -> str: ...
    def __float__(self) -> float: ...
    def __add__(self, other: float | AffineScalarFunc) -> AffineScalarFunc: ...
    def __radd__(self, other: float | AffineScalarFunc) -> AffineScalarFunc: ...
    def __sub__(self, other: float | AffineScalarFunc) -> AffineScalarFunc: ...
    def __rsub__(self, other: float | AffineScalarFunc) -> AffineScalarFunc: ...
    def __mul__(self, other: float | AffineScalarFunc) -> AffineScalarFunc: ...
    def __rmul__(self, other: float | AffineScalarFunc) -> AffineScalarFunc: ...
    def __truediv__(self, other: float | AffineScalarFunc) -> AffineScalarFunc: ...
    def __rtruediv__(self, other: float | AffineScalarFunc) -> AffineScalarFunc: ...
    def __pow__(self, other: float | AffineScalarFunc) -> AffineScalarFunc: ...
    def __neg__(self) -> AffineScalarFunc: ...
    def __pos__(self) -> AffineScalarFunc: ...
    def __abs__(self) -> AffineScalarFunc: ...

def ufloat(
    x: float,
    std_dev: float,
    tag: str | None = ...,
) -> AffineScalarFunc: ...
def nominal_value(x: AffineScalarFunc | float) -> float: ...
def std_dev(x: AffineScalarFunc | float) -> float: ...

# Module-level submodule references
class core:
    AffineScalarFunc = AffineScalarFunc

class unumpy:
    @staticmethod
    def uarray(
        nominal_values: typing.Any,
        std_devs: typing.Any,
    ) -> np.ndarray[typing.Any, np.dtype[typing.Any]]: ...
    @staticmethod
    def nominal_values(
        arr: typing.Any,
    ) -> np.ndarray[typing.Any, np.dtype[typing.Any]]: ...
    @staticmethod
    def std_devs(
        arr: typing.Any,
    ) -> np.ndarray[typing.Any, np.dtype[typing.Any]]: ...
