function set_defaults()
% warnings
% warning("on", "verbose")

% format
format compact

%% Graphics
set(groot, ...
    "DefaultFigureWindowStyle",             "docked", ...  % window style
    ... % "DefaultFigureNumberTitle",             "off", ...  % number title
    "DefaultAxesLooseInset",                [0.05, 0.05, 0.05, 0.075], ...  % axis layout [0.13, 0.11, 0.095, 0.075]
    "DefaultAxesFontSize",                  12, ...  % font size
    ...  % interpreter
    "DefaultAxesTickLabelInterpreter",      "latex", ...
    "DefaultBubblelegendInterpreter",       "latex", ...
    "DefaultColorbarTickLabelInterpreter",  "latex", ...
    "DefaultConstantlineInterpreter",       "latex", ...
    "DefaultGraphplotInterpreter",          "latex", ...
    "DefaultLegendInterpreter",             "latex", ...
    "DefaultPolaraxesTickLabelInterpreter", "latex", ...
    "DefaultTextInterpreter",               "latex", ...
    "DefaultTextarrowshapeInterpreter",     "latex", ...
    "DefaultTextboxshapeInterpreter",       "latex", ...
    ...  % grid
    "DefaultAxesXGrid",                     "on", ...
    "DefaultAxesYGrid",                     "on", ...
    "DefaultAxesZGrid",                     "on", ...
    ...
    "DefaultLineLineWidth",                 0.8 ...
    )

end
