name: Publish (manual)

on:
  workflow_dispatch:
    inputs:
      target:
        description: Repository to upload to
        required: true
        default: testpypi
        type: choice
        options: [testpypi, pypi]

jobs:
  build:
    uses: ./.github/workflows/python-build.yml

  publish-pypi:
    name: Publish to PyPI
    if: inputs.target == 'pypi'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/liron-utils
    permissions:
      id-token: write  # mandatory for PyPI trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1

  publish-testpypi:
    name: Publish to TestPyPI
    if: inputs.target == 'testpypi'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/liron-utils
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
